version: '3.7'
services:
  mongodb_container:
    build: .
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGODB_APPLICATION_DATABASE=comments_manager_module
      - MONGODB_APPLICATION_USER=admin
      - MONGODB_APPLICATION_PASS=admin123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
